### ISSUE TITLE
Handle metadata (rough)

### ISSUE THREAD

**Issue by afflom** [RedHatGov/bundle#15]
- If no metadata found, start new
- If metadata found, load last imageset and append new run to the existing imageset

**Comment by jpower432** [comment]
@afflom @estroz Notes here from our discussion. Will have a metadata file (stat file) that maintains all pertinent information instead of a managed data directory. The data will be ephemeral instead and the metadata will track a history of what is on the disconnected side. This will be passed to the Archiver to determine what to pack. Sound right?
