### ISSUE TITLE
spike: research buildah for building new catalog images

### ISSUE THREAD

**Issue by jpower432** [RedHatGov/bundle#96]
As as admin, I was to use a daemonless options to rebuild the catalog image. Currently we are building it with `docker buildx` being an environmental dependency.

**Comment by afflom** [comment]
Bottom line is that we need do to image builds within this application. This is requirement is due to needing to merge catalog indices during differential publishing operations. We will be using buildah for now, which will lock us into linux only support. Once podman cross-platform matures a bit, we might be able to leverage podman-machine for windows and darwin.

#104
